### ISSUE TITLE
psoftbeat fails if logs directory doesn't exist

### ISSUE THREAD

**Issue by iversond** [UMN-PeopleSoft/psoftbeat#1]
When running `psoftbeat` for the first time, it will throw an error if the `logs` folder doesn't exist.

```
$ ./psoftbeat -E seccomp.enabled=false
panic: open logs/psoftjmx.log: no such file or directory

goroutine 1 [running]:
github.com/inconshreveable/log15.must(...)
        /psoft/admin/userdev/nate-wer/go/src/github.com/inconshreveable/log15/handler.go:340
github.com/inconshreveable/log15.muster.FileHandler(...)
        /psoft/admin/userdev/nate-wer/go/src/github.com/inconshreveable/log15/handler.go:348
github.umn.edu/PSSA/psoftjmx.init.0()
        /psoft/admin/userdev/nate-wer/go/src/github.umn.edu/PSSA/psoftjmx/psoftjmx.go:40 +0xd1
```

The fix is to create the `logs` folder. 

A good permanent solution is to create the folder if it doesn't exist, or deliver an empty `logs` folder in the repo.

**Comment by NateWerner** [comment]
Adding logic auto-create all sub folders.
